# Generated by Django 2.2.2 on 2019-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_bookinorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
