# Generated by Django 2.2.2 on 2019-06-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_bookinorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop_app.Order'),
        ),
    ]
